Fix issue flagged by Wave Accessibility Tool
alphagov/publisher pull request #1556
Opened 2022-03-04 10:32 UTC by davidgisbey

### Description

I've worked through each page of the application and have fixed issues flagged by Wave. This is largely fairly straightforward fixes for things like:

- adding legends/headings to fieldsets
- putting radio buttons in fieldsets
- adding missing labels
- linking labels to inputs where missing
- ensuring headings are sequential

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2022-03-15 15:19 UTC, hannahjump requested changes

2022-03-15 15:19 UTC, hannahjump commented on app/views/shared/_unpublish.html.erb
> +    Unpublishing a page from GOV.UK can not be undone.
I would change to:

If you unpublish a page from GOV.UK it cannot be undone.

2022-03-17 10:41 UTC, brucebolt approved these changes
Looks good to me 👍

2022-03-17 16:25 UTC, davidgisbey commented
Great. Thanks @brucebolt. Just requested a re-review from @hannahjump then i think it'll need someone with admin permissions to merge

2022-03-18 10:36 UTC, hannahjump approved these changes

2022-03-21 15:06 UTC, merged