348 migrate to dart sass
alphagov/publisher pull request #2278
Opened 2024-08-09 10:48 UTC by davidtrussler

[Trello](https://trello.com/c/rtkv3YMZ/348-migrate-mainstream-publisher-to-dart-sass-publisher)

This work makes the necessary changes to migrate Publisher to use Dart Sass. It follows the instructions in [Migrate to Dart Sass from LibSass](https://docs.publishing.service.gov.uk/manual/migrate-to-dart-sass-from-libsass.html).

It is close to the changes made in [PR2250 (Switch from sassc-rails to dartsass-rails)](https://github.com/alphagov/publisher/pull/2250) with a couple of slight changes that seem to fix the issues encountered there, specifically bringing the legacy styles into the SASS Builds folder via the initialiser that is created as part of the work.

2024-08-09 13:04 UTC, mtaylorgds reviewed
Looks good, we just need to make a permission change to the `bin/dev` file and also merge in a change to the `docker-compose.yml` file in the `govuk-docker` repo.

2024-08-09 13:04 UTC, mtaylorgds commented on bin/dev
I think we need to update the permissions on this file (as per [the note in the migration instructions](https://docs.publishing.service.gov.uk/manual/migrate-to-dart-sass-from-libsass.html#:~:text=Note%2C%20you%20might%20see,x%20bin/dev.)).

We will also need to update the `docker-compose.yml` file in the `govuk-docker` repo (which I've raised [a PR](https://github.com/alphagov/govuk-docker/pull/770) for).

2024-08-09 13:26 UTC, mtaylorgds reviewed
[Kevin has commented](https://github.com/alphagov/govuk-docker/pull/770#discussion_r1711430120) on the govuk-docker PR on a better way of running the app, but that will involve some changes to this PR as well. I'm going to see if I can get that working locally.

2024-08-09 13:36 UTC, mtaylorgds requested changes
We're also going to need to make some similar [fixes as were made to Content Tagger](https://github.com/alphagov/content-tagger/pull/1768) to resolve issues with some icons not appearing/appearing corrupted.

![image](https://github.com/user-attachments/assets/5b3f1548-6de6-41e6-82f6-a0cd770c79d3)

2024-08-12 14:00 UTC, davidtrussler commented
> [Kevin has commented](https://github.com/alphagov/govuk-docker/pull/770#discussion_r1711430120) on the govuk-docker PR on a better way of running the app, but that will involve some changes to this PR as well. I'm going to see if I can get that working locally.

I have updated `Procfile.dev` in line with Kevin's suggestions in the Docker [PR770](https://github.com/alphagov/govuk-docker/pull/770). That seems to run fine locally.

2024-08-12 14:17 UTC, davidtrussler commented
> We're also going to need to make some similar [fixes as were made to Content Tagger](https://github.com/alphagov/content-tagger/pull/1768) to resolve issues with some icons not appearing/appearing corrupted.
> 
> ![image](https://private-user-images.githubusercontent.com/138604938/356610271-5b3f1548-6de6-41e6-82f6-a0cd770c79d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjI5NTAsIm5iZiI6MTcyMzQ2MjY1MCwicGF0aCI6Ii8xMzg2MDQ5MzgvMzU2NjEwMjcxLTViM2YxNTQ4LTZkZTYtNDFlNi04MmY2LWEwY2Q3NzBjNzlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxMTM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGRlMWMyNmRjZjc4ZmE0ZDA3NGEzYzk3YmM1ZTcyNzJhY2I5OWMzOTk4MDY3YzljYzAwNzdhZWM2MGIyZTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.33f4c7MRfOpjLOhVGBYj9pjzVOqbJRwYwSU1o6fMyKU)

Ah right, good spot. This seems to be fixed by referencing the Glyphicons font in the legacy-application sass file.

2024-08-27 10:12 UTC, syed-ali-tw approved these changes

2024-08-28 11:17 UTC, davidtrussler commented
> We're also going to need to make some similar [fixes as were made to Content Tagger](https://github.com/alphagov/content-tagger/pull/1768) to resolve issues with some icons not appearing/appearing corrupted.
> 
> ![image](https://private-user-images.githubusercontent.com/138604938/356610271-5b3f1548-6de6-41e6-82f6-a0cd770c79d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDM4NTcsIm5iZiI6MTcyNDg0MzU1NywicGF0aCI6Ii8xMzg2MDQ5MzgvMzU2NjEwMjcxLTViM2YxNTQ4LTZkZTYtNDFlNi04MmY2LWEwY2Q3NzBjNzlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMTEyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmEyMDJlYmQ2NDVlMzI0NTJjZGUxMGEyZmNjM2E0YzQ3ODE5N2QwNmU3NzZiY2ZlYzRhZWI1MTVjZmU1NTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xlL3lkT3O4Gr6WFRXiwpepEb4n3_FjrR-0ksWV2z7uo)

Hello @mtaylorgds - this has been addressed but needs to be marked as such before I am able to merge. Could you have a quick look? Cheers 🙂

2024-08-28 13:49 UTC, merged